apiVersion: v1
kind: Service
metadata:
  name: audio-api
  namespace: audio-api
spec:
  selector:
    app: audio-api
    component: api
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
