apiVersion: v1
kind: Secret
metadata:
  name: audio-api-secret
  namespace: audio-api
type: Opaque
stringData:
  API_KEY: change-me-in-production
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
